// Code generated by hertz generator.

package hello_example

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	hello_example "hello_hertz/biz/model/hello_example"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello_example.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello_example.HelloResp)

	c.JSON(consts.StatusOK, resp)
}

// ByeMethod .
// @router /bye [GET]
func ByeMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req hello_example.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(hello_example.HelloResp)

	c.JSON(consts.StatusOK, resp)
}
